version: "2"
services:
  config-server:
    build: ./config-server
    ports: 
      - 8888:8888
  service-registry:
    build: ./service-registry
    ports: 
      - 1111:1111
    depends_on:
      - config-server