server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/laxuanlinh/microservices-configurations
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:1111/eureka
      registryFetchIntervalSeconds: 5